name: 'Docker Build and Push'
description: 'Build a Docker image and push to Docker Hub'

inputs:
  name-and-tag:
    description: 'Docker image name with tag (e.g., username/image:tag)'
    required: true
  dockerhub-username:
    description: 'Docker Hub username'
    required: true
  dockerhub-password:
    description: 'Docker Hub access token'
    required: true
  context:
    description: 'Docker folder context'
    required: false
    default: '.'  
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: './Dockerfile'
  args:
    description: 'Build arguments'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Debug inputs
      shell: bash
      run: echo "Inputs - name-and-tag:${{ inputs.name-and-tag }}, context:${{ inputs.context }}, dockerfile:${{ inputs.dockerfile }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}

    - name: Build
      id: build_and_push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ inputs.name-and-tag }}
        build-args: ${{ inputs.args }}